parser: babel-eslint
extends: airbnb

env:
  browser: true
  es6: true

rules:
  comma-dangle: [2, never]
  max-len:
    - error
    - 120
    - 2
    - { ignoreUrls: true, ignoreComments: false }
  react/prop-types: 0
